name: Blocklayer

on:
  push:
    branches:
      - master
    paths:
      - 'particubes-dot-com/*'
      - 'particubes-dot-com/*/*'
      - 'particubes-dot-com/*/*/*'
      - 'particubes-dot-com/*/*/*/*'
      - 'particubes-dot-com/*/*/*/*/*'
      - 'particubes-dot-com/*/*/*/*/*/*'
      - 'particubes-dot-com/*/*/*/*/*/*/*'
      - 'particubes-dot-com/*/*/*/*/*/*/*/*'
      - 'particubes-dot-com/*/*/*/*/*/*/*/*/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy particubes.com with Blocklayer
      uses: blocklayerhq/actions@alpha-2
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        api_key: "${{ secrets.BL_API_KEY }}"
        pipeline: "particubes.com"
        inputs: -o git_ref=${{ github.sha }}
