name: Dagger/docs.pr.up

on:
  pull_request:
    types: [opened,synchronize,edited,reopened]
    branches-ignore: [master]
    paths: [lua-docs/**]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_SHA: ${{ github.sha }}
      SSH_PRIVATE_KEY_DOCKER_SWARM: ${{ secrets.SSH_PRIVATE_KEY_DOCKER_SWARM }}
      SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      PULL_REQUEST_ID: ${{ github.event.issue.number }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install Dagger
        uses: dagger/dagger-action@v2
        with:
          install-only: true

      - name: Dagger project update
        run: dagger project update

      - name: Dagger do deploy
        run: dagger do deploy --log-format plain --plan ./lua-docs/docs-pr.cue
